version: "3.4"
services:
  fantom:
    build:
      args:
        VERSION: release/1.0.0-rc.2
      context: ./build/fantom
      dockerfile: Dockerfile
    volumes:
      - "fantom:/datadir"
    ports:
      - "11545:8545"
      - "11546:8546"
      - "41303:30303"
      - "41303:30303/udp"
    restart: unless-stopped
    image: "fantom.public.dappnode.eth:0.1.0"
volumes:
  fantom: {}
