version: "3.4"
services:
  fantom:
    build:
      args:
        VERSION: release/1.0.2-rc.5
      context: ./build/fantom
      dockerfile: Dockerfile
    volumes:
      - "fantom:/datadir"
    ports:
      - "18545:18545"
      - "18546:18546"
      - "5050:5050"
      - "5050:5050/udp"
    restart: unless-stopped
    image: "fantom.public.dappnode.eth:0.1.0"
volumes:
  fantom: {}
